services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      MONGO_URI: mongodb+srv://ajay_user:Ajay12345@cluster0.4xclrc6.mongodb.net/?retryWrites=true&w=majority
      REDIS_HOST: redis

  worker:
    build: .
    command: python -m app.worker
    depends_on:
      - redis
    environment:
      MONGO_URI: mongodb+srv://ajay_user:Ajay12345@cluster0.4xclrc6.mongodb.net/?retryWrites=true&w=majority
      REDIS_HOST: redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"